//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class IntoCSharpParamWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(IntoCSharpParam), typeof(System.Object));
		L.RegFunction("New", _CreateIntoCSharpParam);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("m_intoParam", get_m_intoParam, set_m_intoParam);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateIntoCSharpParam(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				IntoCSharpParam obj = new IntoCSharpParam();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: IntoCSharpParam.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_intoParam(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			IntoCSharpParam obj = (IntoCSharpParam)o;
			LuaInterface.LuaTable ret = obj.m_intoParam;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_intoParam on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_intoParam(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			IntoCSharpParam obj = (IntoCSharpParam)o;
			LuaTable arg0 = ToLua.CheckLuaTable(L, 2);
			obj.m_intoParam = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_intoParam on a nil value");
		}
	}
}

