//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class OutCSharpParamWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(OutCSharpParam), typeof(System.Object));
		L.RegFunction("New", _CreateOutCSharpParam);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("m_outParam", get_m_outParam, set_m_outParam);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateOutCSharpParam(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				OutCSharpParam obj = new OutCSharpParam();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: OutCSharpParam.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_outParam(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			OutCSharpParam obj = (OutCSharpParam)o;
			LuaInterface.LuaTable ret = obj.m_outParam;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_outParam on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_outParam(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			OutCSharpParam obj = (OutCSharpParam)o;
			LuaTable arg0 = ToLua.CheckLuaTable(L, 2);
			obj.m_outParam = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_outParam on a nil value");
		}
	}
}

