//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class PacketWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Packet), typeof(System.Object));
		L.RegFunction("New", _CreatePacket);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("m_bytes", get_m_bytes, set_m_bytes);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreatePacket(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Packet obj = new Packet();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Packet.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_bytes(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Packet obj = (Packet)o;
			byte[] ret = obj.m_bytes;
			LuaDLL.tolua_pushlstring(L, ret, ret.Length);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_bytes on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_bytes(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Packet obj = (Packet)o;
			byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
			obj.m_bytes = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_bytes on a nil value");
		}
	}
}

